### ISSUE TITLE
E-Mails with more the 225 Recipients fail

### ISSUE THREAD

**Issue by fahrstuhl1** [MailCleaner/MailCleaner#359]
If an email with more than 225 recipeints is send to the mailcleaner we get the following error message in the exim_stage1/mainlog and paniclog:

```
string_sprintf expansion was longer than 32768; format string was (%s : %s)
 called from setup_remove_header 1075
```
everything under 225 recipients works just fine.
Our e-mails are coming from an exchange server, the email will never be delivered or queued in one of the Mailcleaner Queues because it fails to submit it with the following error

`421 Unexpected failure, please try later`

in versions prior to 2021052101 we dont have that problem.
So for now an E-Mail with more than 225 Recipients cant be send through our Mailcleaner.

**Comment by bogdankruszewski** [comment]
I can see the same issue since few months, too. @fahrstuhl1, have you tested if it's only related to "BCC" or also to "TO" and "CC" recipients? I've traced the code changes in exim regarding the function "setup_remove_header", but nothing has changed since years there. So I suppose than some changes to the Exim template files which were updated with v. 4.94 are causing this issue.

This is really annoying as you mention, because Exim throws a 4xx error, which cause the Exchange servers behind Mailcleaner to try again for the next 2 days again and again. This will fill up the Mailcleaner logs and the sender will get an NDR from the Exchange server 2 days later for an e-mail, where we already now that it will never be delivered from the beginning.

**Comment by fahrstuhl1** [comment]
@bogdankruszewski  
in our case it was for every mail it did not matter if "BCC", "TO" or "CC".
We are now working around this by completly removing the `___INCLUDE___ `in line 328 in the exim_stage1.conf_template and added some of the content to the template file.
![exim_stage1 conf_template-Changes](https://user-images.githubusercontent.com/6241560/164190841-a7147601-a1d4-44ef-b0e8-8749c7f3c419.png)

**Comment by bogdankruszewski** [comment]
@fahrstuhl1, thanks for the information. I will take a look on it. 

By the way: please note, that your workaround could stop work, if my pull request #441 will be accepted, because until now (without the fix) the __ IF __ __ LISTS_PER_DOAMIN ___ will never be executed. You can check, if the __ IF __ clause will be "true" in your environment with `echo "SELECT count(*) FROM wwlists where type in ('black-ip-dom', 'spam-ip-dom', 'white-ip-dom', 'wh-spamc-ip-dom')" | /usr/mailcleaner/bin/mc_mysql -m mc_config` via SSH. If count = 0, then your workaround should still work.

**Comment by bogdankruszewski** [comment]
@JohnMertz & @reivilob , maybe I don't understand something, but why there is a need to use "remove_header" in exim_stage1.conf, which seems to cause some issues already at incoming SMTP stage?

Why is it neccessary for example to remove this header in https://github.com/MailCleaner/MailCleaner/blob/master/etc/exim/exim_stage1.conf_template_4.94#L362?
As far as I understand, the other two "warn spf" above won't add any header to be removed, if the third "warn spf" will hit, there shouldn't be any header to be removed, should it?

Another example:
In https://github.com/MailCleaner/MailCleaner/blob/master/etc/exim/stage1/remove_headers_template the header X-MailCleaner-TrustedIPs will be removed in stage 1 (incoming stage). So this header will never hit this line in Mailscanners prefilters here https://github.com/MailCleaner/MailCleaner/blob/master/lib/MailScanner/PreFilters/TrustedIPs.pm#L52 and therefore this if clause will never get "true" in my opinion.

Maybe it would be a better idea to remove headers, which are not needed for some reasons at Exims stage 4 (outgoing stage)? Don't know if this will also hit this issue here in the outgoing stage, but right now we don't even have a message stuck in any stage to debug it, because MailCleaner is rejecting such messages with a 4xx error ("please try later").

**Comment by JohnMertz** [comment]
This should be fixed since #492

Options were added for how to handle invalid long lines in Configuration->SMTP->SMTP Checks to ignore the errors and relay the invalid SMTP, correct the long lines by splitting them at a configurable length (1000 by default), or to reject the message for having invalid long lines (the behaviour prior to this feature).

**Comment by bogdankruszewski** [comment]
Hi @JohnMertz,

I need to reopen this issue, because the root cause is not the invalid SMTP lenght.
As @fahrstuhl1 and I traced this issue two years ago, the issue is located in the remove_header function in the exim_stage1.conf_template_4.97 and still exists.

We still can see messages with 421 error hanging in our Exchange spools, because MailCleaner don't want to accept them for relay, if they have more recipient address chars than 32768.

Best regards

Bogdan

**Comment by Gileraracer** [comment]
We have the same Problem still with the latest mailcleaner version when sending mails to > 225 recipients

**Comment by JohnMertz** [comment]
Sorry, it's been a long time since I looked at this, but I'm pretty sure I was wrong about my solution fixing this specific issue. The line wrapping will resolve Exim rejecting headers that are too long, but this specific issue is actually caused during Exim string expansion, not the reading in of headers.

Specifically, at some point Exim is trying to expand a variable (probably `$recipients`) which is too long for it to operate on (. This is a hard limit inside of Exim, not something that we have control over. The only way that we could avoid this issue is to avoid ever trying to expand that variable. However, the existing uses of that variable are quite necessary for different functionality. eg. We write a X-MailCleaner-recipients header in Stage 1 which is used by MailScanner and SpamC to get a canonical list of all recipients, which is then removed in Stage 4 for privacy.

Realistically, this should probably be handled by limiting the maximum number of recipients per transaction to a value which should never hit this limit (say, 100; ~225 is not a fixed number, just the approximation of 32768/average_email_length_in_bits, so you'd want to leave a healthy margin for cases where many addresses are above average length).

If you set the limit in SMTP->Resource Controls->Maximum number of recipients, the connecting machine should respect that limit and break it into two or more separate messages (perhaps even during the same connection). Howe each MTA handles this may be different, but it is common to have a recipient limit, so they should all be capable of dealing with it.
