### ISSUE TITLE
High memory usage after upgrade exim

### ISSUE THREAD

**Issue by mvldebian** [MailCleaner/MailCleaner#370]
After upgrading to the latest version of exim the memory usage grows without limits, even crashing the host.

![Seleção_022](https://user-images.githubusercontent.com/25337130/128044762-b7b6ca73-0574-49f1-8d0c-b408fbc35fe3.png)

I was forced to downgrade to continue using.

Are there any related reports in this new version related to this excessive use of memory? the host has 8gb of ram and I believe it's more than necessary...

**Comment by JohnMertz** [comment]
Hello,

This was after upgrading using our build of 4.94.2 (package name mc-exim) ?

It is not an issue I've seen anywhere else and we released that package a while ago, so this seems odd.

Beyond that, did you confirm that it was actually exim that was using the memory, for example by using `top`? If so, do you see any strange output by watching the logs?:

    $ tail -f /var/mailcleaner/log/exim_stage?/mainlog

Things like timeouts or rapidly repeating attempts to do intensive tasks might provide a hint at what is actually causing the issue.

**Comment by mvldebian** [comment]
I tried again to use the version mentioned, but I still have a problem with cpu and memory usage.
In the logs of stage 2, several entries are generated as below, I have already verified that the configuration of the limits are the same in both the old and the new versions, but when updating this always happens.


2022-01-17 09:03:20 temporarily refused connection from a11-147.smtp-out.amazonses.com [54.240.11.147]: not in reserve list and load average = 55.20
2022-01-17 09:03:20 temporarily refused connection from hm1480-11.locaweb.com.br [201.76.49.108]: not in reserve list and load average = 55.20
2022-01-17 09:03:20 temporarily refused connection from a48-61.smtp-out.amazonses.com [54.240.48.61]: not in reserve list and load average = 55.20
2022-01-17 09:03:20 temporarily refused connection from a48-62.smtp-out.amazonses.com [54.240.48.62]: not in reserve list and load average = 55.20
2022-01-17 09:03:21 temporarily refused connection from a48-49.smtp-out.amazonses.com [54.240.48.49]: not in reserve list and load average = 55.20
2022-01-17 09:03:21 temporarily refused connection from mail49213.hm1479.locaweb.com.br [201.76.49.213]: not in reserve list and load average = 55.20
2022-01-17 09:03:21 temporarily refused connection from mail112244.hm1479.locaweb.com.br [189.126.112.244]: not in reserve list and load average = 55.20
2022-01-17 09:03:22 temporarily refused connection from xc30.dietfitnutri.com [5.188.36.141]: not in reserve list and load average = 55.20
2022-01-17 09:03:22 temporarily refused connection from hm1480-12.locaweb.com.br [201.76.49.109]: not in reserve list and load average = 55.20
2022-01-17 09:03:22 temporarily refused connection from mail494.hm1479.locaweb.com.br [201.76.49.4]: not in reserve list and load average = 55.59
2022-01-17 09:03:22 temporarily refused connection from mail4910.hm1479.locaweb.com.br [201.76.49.10]: not in reserve list and load average = 55.59
2022-01-17 09:03:22 temporarily refused connection from mail49191.hm1315.locaweb.com.br [201.76.49.191]: not in reserve list and load average = 55.59
2022-01-17 09:03:23 temporarily refused connection from mail49214.hm1479.locaweb.com.br [201.76.49.214]: not in reserve list and load average = 55.59
2022-01-17 09:03:23 temporarily refused connection from mail112245.hm1479.locaweb.com.br [189.126.112.245]: not in reserve list and load average = 55.59
2022-01-17 09:03:24 temporarily refused connection from hm1480-13.locaweb.com.br [201.76.49.110]: not in reserve list and load average = 55.59

**Comment by mvldebian** [comment]
Any other tips?

I still can't use the current version of exim, whenever I update the exaggerated consumption ends up causing me to force the downgrade.

**Comment by mvldebian** [comment]
Any suggestion ?

I still couldn't update exim due to this problem...

**Comment by JohnMertz** [comment]
I was never able to replicate this issue. Can you tell me if it is still a problem with Exim 4.96?
