### ISSUE TITLE
Tracing Log indicates missing files in filtering engine

### ISSUE THREAD

**Issue by Brauadler** [MailCleaner/MailCleaner#473]
After yesterdays commit went live on my Mailcleaner instance, the tracing log indicates that files are missing.

![grafik](https://user-images.githubusercontent.com/95625809/181696183-27b760ee-ad74-4f25-bf3d-581b21ff4446.png)

I assume that the clean_ms_tmp file and the cron job are to blame. So far I haven't seen any major impact on my system, but wanted to point that out.

**Comment by JohnMertz** [comment]
Thanks. Resolved by #476

**Comment by Brauadler** [comment]
Unfortunately, #476 did not fix the issue. After running the commands from _bin/ms_tmp-cleaner_ one by one on my MC instance without deleting, i found that the following code fragment triggers the error by periodically deleting the empty numeric folders in the incoming subfolder.
 
`find /var/mailcleaner/spool/tmp/mailscanner -type d -empty -delete`

These are probably still needed by the mailscanner. After commenting out this command, the warnings in the log stopped.

**Comment by JohnMertz** [comment]
Sorry. That line was redundant after the last change anyways. Removed in this commit: https://github.com/MailCleaner/MailCleaner/commit/552535b2cfe9f27dd2b5cea8e7868978fe725cb8
